<!DOCTYPE html>
<html>
<head>
	<title>promise语法</title>
</head>
<body>
<script type="text/javascript">
	/** Promise:
		-- resolve作用: 将 Promise 对象的状态 从 "未完成" 变为 "成功", 在异步操作成功时调用, 并将异步操作的结果, 作为参数传递出去

		-- reject作用: 将 Promise 对象的状态 从 "未完成" 变为 "失败", 在异步操作时调用, 并将异步操作报出的错误作为参数传递出去

		当 Promise 状态改变时, 就会触发 .then() 里面的回调函数 来处理后续步骤, Promise状态一经改变就不会更改
	 */
	new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve('1')
		}, 100)
	}).then(
		res => {
			console.log(res)
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					resolve('2')
				}, 400)
			})
		},
		err => {console.log(err)}
	).then(res => {
		console.log(res)
	})

	/** 可将 Promise 实例作为一个变量传递到其他的地方 */
	let promise = new Promise(resolve => {
		setTimeout(() => {
			resolve('变量保存Promise实例, 用于传递')
		}, 1000)
	})
	setTimeout(() => {
		promise.then(res => {
			console.log(res);
		})
	}, 0)

	/** .then() 嵌套包含 .then()
			.then() 返回的还是 Promise 对象
	 */
	new Promise((resolve) => {
		console.log('步骤一');
		setTimeout(() => {
			resolve('1');
		}, 1500)
	}).then(res => {
		return new Promise(resolve => {
			console.log('步骤1-1', res);
			setTimeout(() => {
				resolve('1-1');
			}, 500)
		}).then(res => {
			console.log('步骤1-2', res);
			return res // 1-1
		}).then(res => {
			console.log('步骤1-3', res);
			return res // 1-1
		})
	}).then(res => {
		console.log('步骤2', res);
	})

	/** 上面的 .then() 包含 .then() 写法可展开改写为: 

		new Promise(resolve => {
			console.log('步骤一');
			setTimeout(() => {
				resolve('1');
			}, 1500)
		}).then(res => {
			return new Promise(resolve => {
				console.log(步骤1-1, res);
				setTimeout(() => {
					resolve('1-1')
				}, 500)
			})
		}).then(res => {
			console.log('步骤1-2', res);
			return res
		}).then(res => {
			console.log('步骤1-3', res);
			return res
		}).then(res => {
			console.log('步骤2', res);
		})
	*/

	/** Promise 错误处理: 有问题,,,,,
		第一种: 通过 new Error() 实现; 通过 .catch() 接收; catch() 也会返回一个 promise 实例, 摒弃是 resolved状态
	 */
	
	new Promise(resolve => {
		setTimeout(() => {
			throw new Error('bye');
		}, 3000)
	}).then(res => {
		// new Error('通过 new Error 处理错误');
	}).catch(err => {
		console.log(err);
	})
	
	/** promise 错误处理: 
		第二种: 通过 reject() 实现
	 */
	new Promise((resolve, reject) => {
		setTimeout(() => {
			reject('通过reject 实现 错误处理')
		}, 3500)
	}).then(res => {}, err => {console.log(err)})
</script>
</body>
</html>